### ISSUE TITLE
“by setting $\zeta  = ...$” does not sound correct, because Vardi does not set $\zeta$

### ISSUE THREAD

**Issue by zaikunzhang** [ragonneau/phd-thesis#24]
https://github.com/ragonneau/phd-thesis/blob/da18a8c805481e89a267eed793067ab9410fc8a0/content/sqp.tex#L818

by setting~$\zeta = \norm{\nstep[k]} / \rad[k]  = \alpha \norm{\step[\ast]} / \rad[k]$.
---> if~$\zeta = \norm{\nstep[k]} / \rad[k]  = \alpha \norm{\step[\ast]} / \rad[k]$.

**Comment by ragonneau** [comment]
I changed to
```latex
Therefore, the normal step~$\nstep[k]$ of the Vardi approach is a truncated Newton step for the normal subproblem~\cref{eq:byrd-omojokun-original} if~$\zeta = \norm{\nstep[k]} / \rad[k]  = \alpha \norm{\step[\ast]} / \rad[k]$.
```
