### ISSUE TITLE
Two mistakes in the most recent commit "Patch #37, #39, and #40"

### ISSUE THREAD

**Issue by zaikunzhang** [ragonneau/phd-thesis#41]
See my comments on the most recent commit. Thanks.

**Comment by zaikunzhang** [comment]
I corrected them. Tell me if I misunderstood something.

**Comment by ragonneau** [comment]
@zaikunzhang, I do not understand why they are mistakes. I did both on purpose, but maybe my English is mistaken.

**Comment by zaikunzhang** [comment]
Did you read my comments?
